<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>5fb2f0f6-e5b8-4fc9-ab81-ea2e4810f59f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='header']/div/div/div/div/div/a/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>a >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a5022ba3-d6a6-4687-b66c-18bc256bd517</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>bsip-logo-1.png</value>
      <webElementGuid>c4036928-b342-407e-b721-a14fa459b5e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;header-nav&quot;]/div[@class=&quot;header-nav-wrapper navbar-scrolltofixed scroll-to-fixed-fixed&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row responsive-header-top&quot;]/div[@class=&quot;col-xs-12 col-sm-12 col-md-6&quot;]/a[1]/div[1]/img[1]</value>
      <webElementGuid>3d2f628d-6d92-40ae-b466-e737c73c6e26</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='header']/div/div/div/div/div/a/div/img</value>
      <webElementGuid>5132c7ee-aa08-4082-8089-6d3cd44e66e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>50f8ff2a-c151-4c30-a480-cc9548654ff7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'bsip-logo-1.png']</value>
      <webElementGuid>615a43cb-eeef-4376-a6a3-b08c0a3b413c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
