<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Museum</name>
   <tag></tag>
   <elementGuidId>37bf38b0-4c55-48bc-aff8-019ee5afff61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(7) > ul.dropdown > li > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='menuzord']/ul/li[7]/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Museum&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>574500a9-1a44-44cd-8861-b8dabb52e551</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>bsip_museum.php</value>
      <webElementGuid>68773218-79c6-4f59-b073-9c29ccfbe060</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Museum</value>
      <webElementGuid>f8cbea99-d9bd-40d7-9329-17881f58a1f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;menuzord&quot;)/ul[@class=&quot;menuzord-menu menuzord-indented scrollable&quot;]/li[7]/ul[@class=&quot;dropdown&quot;]/li[1]/a[1]</value>
      <webElementGuid>356946aa-9c99-4924-b478-c22f0798f5ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='menuzord']/ul/li[7]/ul/li/a</value>
      <webElementGuid>e1ae5888-b9d1-43eb-a9c7-61c324abc6c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Museum')]</value>
      <webElementGuid>8ccd0325-fd9e-4ad0-b185-d67a72a8b01a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Units'])[1]/following::a[1]</value>
      <webElementGuid>7ad29aaa-c07c-4d31-b745-19c4d5cb1424</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Newsletter'])[1]/following::a[2]</value>
      <webElementGuid>a47b9744-8a4d-419d-82f7-e898b4941105</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Knowledge Resource Centre'])[1]/preceding::a[1]</value>
      <webElementGuid>486248e8-a3cf-496a-98a4-6033817d6eae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Computer Section'])[1]/preceding::a[2]</value>
      <webElementGuid>ee91c479-e8b2-4204-931f-32d8a7cf8b1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Museum']/parent::*</value>
      <webElementGuid>6d60d896-39cd-41e1-8735-2cd3744b09ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'bsip_museum.php')]</value>
      <webElementGuid>9a6df11a-96f0-4e30-98b0-21a6e27bd74d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/ul/li/a</value>
      <webElementGuid>e002cdb8-c8d8-4e25-9bda-669d29f706f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'bsip_museum.php' and (text() = 'Museum' or . = 'Museum')]</value>
      <webElementGuid>b36325b7-d6b3-4b46-8c07-1cc0a084eb6a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
