<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Repository</name>
   <tag></tag>
   <elementGuidId>3529d94e-6783-4dec-8b7f-ec50e7cba4de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>ul.angle-double-right.list-border > li:nth-of-type(3) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wrapper']/div[2]/footer/div/div/div[2]/div/ul/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Repository&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>125ecfd9-c415-48c9-b5cc-8f74e7a580bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>http://14.139.63.228:8080/pbrep/</value>
      <webElementGuid>8089746e-ed0e-4502-b239-c000d0fa833d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Repository</value>
      <webElementGuid>bd10da99-3270-41fc-bf5e-98eda0c371f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wrapper&quot;)/div[@class=&quot;main-content&quot;]/footer[@class=&quot;footer&quot;]/div[@class=&quot;container-fluid pt-20 pb-10&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-6 col-md-3 responsive-header-top&quot;]/div[@class=&quot;widget dark&quot;]/ul[@class=&quot;angle-double-right list-border&quot;]/li[3]/a[1]</value>
      <webElementGuid>1393e276-8c79-406f-ac61-94d11a91fe4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper']/div[2]/footer/div/div/div[2]/div/ul/li[3]/a</value>
      <webElementGuid>b356cb1c-aad7-48d8-b727-96e41e9b22c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Repository')]</value>
      <webElementGuid>2ae540e1-fde2-442a-a30e-043d526f54d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Catalogue'])[1]/following::a[1]</value>
      <webElementGuid>91f4c86a-9c84-4881-a224-bd6f4ddcab55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RTI'])[1]/following::a[2]</value>
      <webElementGuid>2379e1a4-accc-4696-b640-3ffdd49b7a53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BSIP News'])[1]/preceding::a[1]</value>
      <webElementGuid>06d30fe1-9af9-42ed-9590-f3d41cd8614a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BSIP Outreach Program'])[1]/preceding::a[2]</value>
      <webElementGuid>f870c864-dc95-49aa-aafb-1fdde6c1eb53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Repository']/parent::*</value>
      <webElementGuid>6697a31e-818e-48af-9db8-8bb92295233a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[@href='http://14.139.63.228:8080/pbrep/']</value>
      <webElementGuid>72011c7b-4a1b-4285-b8ef-1a5932a4472b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/ul/li[3]/a</value>
      <webElementGuid>3ef55684-eb11-4d34-b84a-8f7048af0ba0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'http://14.139.63.228:8080/pbrep/' and (text() = 'Repository' or . = 'Repository')]</value>
      <webElementGuid>c354975f-9f30-488a-9c0e-1f9d386c9ce5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
